import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/Layout";

import { api } from "~/utils/api";
import Login from "./Login";
import SignUp from "./SignUp";
import Categories from "./Categories";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Login /> */}
        {/* <SignUp /> */}
        <Categories />
      </Layout>
    </>
  );
}
