import Head from "next/head";
import Layout from "~/components/Layout";

import { api } from "~/utils/api";
import Login from "./Login";
// import SignUp from "./SignUp";
import Categories from "../components/Categories";
import { generateItems } from "~/utils/generateData";

export default function Home() {
  const createData = api.post.createCategories.useMutation();
  //const getData = api.post.getLatest.useQuery({ page: 37 });

  return (
    <>
      <Head>
        <title>Moonshot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Layout>
        <Login />
        <SignUp />
        <Categories />

        <button onClick={async () => createData.mutate(generateItems(90))}>
          Submit
        </button> 
      </Layout> */}
      <Categories />
    </>
  );
}
