import Head from "next/head";
import Layout from "~/components/Layout";

import { api } from "~/utils/api";
// import Login from "./Login";
// import SignUp from "./SignUp";
import Categories from "./Categories";
import { generateItems } from "~/utils/generateData";

export default function Home() {
  const createData = api.post.create.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Login /> */}
        {/* <SignUp /> */}
        <Categories />

        <button
          onClick={async () =>
            createData.mutate({ category_name: "Dinesh Movie", selected: true })
          }
        >
          Submit
        </button>
      </Layout>
    </>
  );
}
